import 'leaflet/dist/leaflet.css';
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar"; // adjust path if needed
import SessionProviderWrapper from "../components/provider/SessionProviders"; // adjust path if needed
import "./globals.css";
import Footer from '../components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Car Parking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <Navbar />

          {/* Add spacing between Navbar and Footer */}
          <div className="mt-15 mb-5">
            {children}
          </div>

          <Footer />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}

